### PR TITLE
add Scala 2.13.0-M5 to cross-build

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by alexarchambault** [comment]
ping @lihaoyi

**Comment by lihaoyi** [comment]
@alexarchambault gave you commit access, since you seem to be doing a lot of 213 related stuff feel free to go wild

**Comment by alexarchambault** [comment]
@SethTisue Couldn't we manage not to rely on sbt-buildinfo, or at least not have it add public stuff in the main module? The scala version is already available via `scala.util.Properties.versionNumberString` (may require forking in tests to work right), and the cross stuff could be deduced via platform-specific sources under `geny/{js, jvm}/src/`.

**Comment by lihaoyi** [comment]
Honestly I'd just be happy with it saying `x == "WrappedArray(...)" || x == "WrappedVarArgs(...)"`. The chances of that looseness causing a regression to slip through are just about zero

**Comment by ajrnz** [comment]
This should be implemented by #7 - shout if not

**Pull request closed without merging**
