### PR TITLE
Upgrade Scala 3 to M3

### PR DESCRIPTION
**Pull request by anatoliykmetyuk**

### CODE REVIEW

**Review by jodersky — APPROVED** [review]
It works on my machine (OpenJDK 11). Looking at the travis error message, could it be that utest was published on java 11 (instead of 8)?

**Comment by lolgab** [comment]
> It works on my machine (OpenJDK 11). Looking at the travis error message, could it be that utest was published on java 11 (instead of 8)?

It is it,
I faced the same problem updating other things.

**Comment by jodersky** [comment]
I confirmed this with @anatoliykmetyuk. This will be fixed once a new release of Dotty is published.

**Comment by lolgab** [comment]
Geny has been released to Scala 3.0.0-M3, compiled with a JDK 8 .
The version 0.6.5 is on Maven central.

**Comment by jodersky** [comment]
Excellent! Then we can close this

**Pull request closed without merging**
