### PR TITLE
Dotty build

### PR DESCRIPTION
**Pull request by jodersky**
The changes here are from the dotty community build.

utest is already available publicly for dotty 0.26.0-RC1

### CODE REVIEW

**Comment by jodersky** [comment]
I don't have permission to restart the CI build unfortunately. It passes on my machine, for what it's worth.

**Comment by anatoliykmetyuk** [comment]
After restarting the build, this fails with:

```
[error] -- Error: /home/travis/build/lihaoyi/geny/geny/test/src/geny/TestGenerator.scala:21:14 
1747[error] 21 |        assert(toSeq == expected)
1748[error]    |        ^^^^^^^^^^^^^^^^^^^^^^^^^
1749[error]    |Exception occurred while executing macro expansion.
1750[error]    |dotty.tools.dotc.core.CyclicReference: 
1751[error]    |	at dotty.tools.dotc.core.CyclicReference$.apply(TypeErrors.scala:155)
1752[error]    |	at dotty.tools.dotc.core.SymDenotations$SymDenotation.completeFrom(SymDenotations.scala:164)
```

**Comment by jodersky** [comment]
Very strange that it worked on my machine. I'll look into it

**Comment by jodersky** [comment]
@anatoliykmetyuk I can't reproduce the failure locally. Could it be related to the utest assert issue we discussed the other day? Is it possible that the dotty-staging repo of utest has a fix which has not been upstreamed to utest official?

**Comment by jodersky** [comment]
I added a workaround in my latest commit anyway

**Comment by anatoliykmetyuk** [comment]
> Is it possible that the dotty-staging repo of utest has a fix which has not been upstreamed to utest official?

Yes, I believe this is the case. Since utest has already been released for Dotty 0.26.0-RC1, we'll wait until the next Dotty release to incorporate the missed changes.

**Pull request merged**
